#!/bin/bash

set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

HEKA_VERSION="0.10.0"
COLLECTOR_TAG="0.10.0"

# Hindsight packages

 download_packages \
    http://172.18.162.63/mos-repos/ubuntu/9.0/pool/main/h/hindsight/hindsight_0.9.0-1~ub14.04%2bmos2_amd64.deb \
    http://172.18.162.63/mos-repos/ubuntu/9.0/pool/main/libr/librdkafka/librdkafka1_0.9.1-1~ub14.04%2bmos1_amd64.deb \
    http://172.18.162.63/mos-repos/ubuntu/9.0/pool/main/l/lua-sandbox/libluasandbox1_1.0.3-5~ub14.04%2bmos1_amd64.deb \
    http://172.18.162.63/mos-repos/ubuntu/9.0/pool/main/l/lua-sandbox/libluasandbox-dev_1.0.3-5~ub14.04%2bmos1_amd64.deb \
    http://172.18.162.63/mos-repos/ubuntu/9.0/pool/main/l/lua-sandbox-extensions/lua-sandbox-extensions_0.0~git20160812.98065e76-1~ub14.04%2bmos3_amd64.deb

# Download Heka deb package

download_packages \
    https://github.com/elemoine/heka/releases/download/ratelimit-1/heka_${HEKA_VERSION}_amd64.deb
check_md5sum heka_${HEKA_VERSION}_amd64.deb 69514d94173181a8d1dcab769062fdac

# Download Heka puppet module from lma collector plugin

URL="https://github.com/openstack/fuel-plugin-lma-collector/archive/${COLLECTOR_TAG}.tar.gz"
HEKA_MODULE_PATH="fuel-plugin-lma-collector-${COLLECTOR_TAG}/deployment_scripts/puppet/modules/heka"
DESTINATION=deployment_scripts/puppet/modules
TEMP_DIR=`mktemp -u`
download_file $URL $COLLECTOR_TAG.tar.gz $TEMP_DIR
tar -xf $TEMP_DIR/$COLLECTOR_TAG.tar.gz -C $DESTINATION --strip-components=4 $HEKA_MODULE_PATH
rm -fr $TEMP_DIR