#!/bin/bash

set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

HEKA_VERSION="0.10.0"

download_packages \
    https://github.com/elemoine/heka/releases/download/ratelimit-1/heka_${HEKA_VERSION}_amd64.deb

check_md5sum heka_${HEKA_VERSION}_amd64.deb 69514d94173181a8d1dcab769062fdac

# Download Heka puppet module from lma collector plugin

URL=https://github.com/openstack/fuel-plugin-lma-collector/archive/0.10.0.tar.gz
HEKA_MODULE_PATH=fuel-plugin-lma-collector-0.10.0/deployment_scripts/puppet/modules/heka
DESTINATION=deployment_scripts/puppet/modules
TEMP=`mktemp -u`
download_file $URL 0.10.0.tar.gz $TEMP
tar -xf $TEMP/0.10.0.tar.gz -C $DESTINATION --strip-components=4 $HEKA_MODULE_PATH